package com.ecommerce.service;

import com.ecommerce.model.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.*;
import java.util.*;

public class ReturnService {
 private final OrderService orderService; private final InventoryService inventoryService; private final NotificationService notificationService; private final Map<Integer,ReturnRecord> records=new LinkedHashMap<>(); private final Path file=Paths.get("data","returns.dat"); private final EmailService email=new EmailService();
 public ReturnService(OrderService os,InventoryService is){orderService=os;inventoryService=is;notificationService=os==null?new NotificationService():os.getNotificationService();load();}
 public synchronized boolean requestReturn(int id,String reason){Order o=orderService==null?null:orderService.findOrderById(id);if(o==null||o.getStatus()!=OrderStatus.DELIVERED||records.containsKey(id))return false; ReturnRecord r=new ReturnRecord(id,o.getCustomer()==null?"":o.getCustomer().getEmail(),reason==null||reason.isBlank()?"Customer request":reason.trim());records.put(id,r);o.updateStatus(OrderStatus.RETURN_REQUESTED);save(); notifyCustomer(o,NotificationType.RETURN_REQUESTED,returnMessage(o,r));return true;}
 public synchronized boolean schedulePickup(int id,LocalDateTime when){ReturnRecord r=records.get(id);Order o=order(id);if(r==null||o==null||when==null||r.getStatus()!=ReturnStatus.REQUESTED)return false;r.setPickupDate(when);r.setStatus(ReturnStatus.PICKUP_SCHEDULED);save();notifyCustomer(o,NotificationType.RETURN_REQUESTED,"Your SAIVEE return for order #"+id+" has a pickup scheduled for "+when+". Please keep the item, tags and accessories ready and request a pickup receipt.");return true;}
 public synchronized boolean markPickedUp(int id){ReturnRecord r=records.get(id);Order o=order(id);if(r==null||o==null)return false;r.setStatus(ReturnStatus.PICKED_UP);save();notifyCustomer(o,NotificationType.RETURN_REQUESTED,"SAIVEE has recorded pickup of the return for order #"+id+". The item will now move to inspection.");return true;}
 public synchronized boolean startInspection(int id){ReturnRecord r=records.get(id);Order o=order(id);if(r==null||o==null)return false;r.setStatus(ReturnStatus.UNDER_INSPECTION);save();notifyCustomer(o,NotificationType.RETURN_REQUESTED,"The returned item for order #"+id+" is under inspection. We will email you once the return decision is recorded.");return true;}
 public synchronized boolean approveReturn(int id){ReturnRecord r=records.get(id);Order o=order(id);if(r==null||o==null||r.getStatus()!=ReturnStatus.UNDER_INSPECTION&&r.getStatus()!=ReturnStatus.PICKED_UP)return false;r.setStatus(ReturnStatus.APPROVED);o.updateStatus(OrderStatus.RETURNED);restoreStockOnce(o);save();notifyCustomer(o,NotificationType.RETURN_REQUESTED,"Your return for SAIVEE order #"+id+" has been approved after inspection. Refund processing will now begin according to your payment method.");return true;}
 public synchronized boolean rejectReturn(int id,String notes){ReturnRecord r=records.get(id);Order o=order(id);if(r==null||o==null)return false;r.setStatus(ReturnStatus.REJECTED);r.setInspectionNotes(notes==null?"Return did not meet return conditions.":notes);o.updateStatus(OrderStatus.DELIVERED);save();notifyCustomer(o,NotificationType.RETURN_REQUESTED,"Your return request for SAIVEE order #"+id+" was not approved after inspection. Reason: "+r.getInspectionNotes());return true;}
 public synchronized boolean refund(int id){ReturnRecord r=records.get(id);Order o=order(id);if(r==null||o==null||r.getStatus()!=ReturnStatus.APPROVED)return false;r.setStatus(ReturnStatus.REFUND_PROCESSING);r.setRefundReference("RFN-"+System.currentTimeMillis());o.updateStatus(OrderStatus.REFUNDED);r.setStatus(ReturnStatus.REFUNDED);save();notifyCustomer(o,NotificationType.REFUND_PROCESSED,refundMessage(o,r));return true;}
 public synchronized ReturnRecord getRecord(int id){return records.get(id);} public synchronized List<ReturnRecord> getRecords(){return List.copyOf(records.values());}
 private Order order(int id){return orderService==null?null:orderService.findOrderById(id);}
 private void restoreStockOnce(Order o){for(OrderItem item:o.getOrderItems()){if(item==null||item.getProduct()==null)continue;if(item.getVariantKey()==null||item.getVariantKey().isBlank())inventoryService.restoreStock(item.getProduct(),item.getQuantity());else inventoryService.restoreVariantStock(item.getProduct(),item.getQuantity(),item.getVariantKey());}}
 private void notifyCustomer(Order o,NotificationType t,String msg){if(o.getCustomer()!=null&&notificationService!=null)notificationService.sendNotification(700000+o.getOrderId(),o.getCustomer(),t,msg);}
 private String returnMessage(Order o,ReturnRecord r){return "Your SAIVEE return request for order #"+o.getOrderId()+" has been received. Reason: "+r.getReason()+". Next: pickup scheduling, pickup, inspection, approval/rejection, then refund processing if approved. For prepaid orders, eligible refunds go back to the original payment method. For COD returns where payment was collected, an eligible refund is arranged by verified bank transfer after approval. This message confirms the request only; it does not confirm pickup, approval or refund completion.";}
 private String refundMessage(Order o,ReturnRecord r){return "Your SAIVEE refund for order #"+o.getOrderId()+" is completed. Refund reference: "+r.getRefundReference()+". For prepaid orders, the amount is sent back through the original payment channel; your bank/payment provider may take several business days to post it. For an eligible COD return, the approved refund is recorded for bank transfer to the verified refund account. Please use the refund reference for support queries.";}
 private void save(){try{Files.createDirectories(file.getParent());List<String> lines=new ArrayList<>();for(ReturnRecord r:records.values())lines.add(r.getOrderId()+"|"+b(r.getCustomerEmail())+"|"+b(r.getReason())+"|"+r.getStatus()+"|"+(r.getPickupDate()==null?"":r.getPickupDate())+"|"+b(r.getInspectionNotes())+"|"+b(r.getRefundReference()));Files.write(file,lines,StandardCharsets.UTF_8);}catch(Exception e){System.out.println("Return history save failed: "+e.getMessage());}}
 private void load(){if(!Files.exists(file))return;try{for(String s:Files.readAllLines(file,StandardCharsets.UTF_8)){String[] x=s.split("\\|",-1);if(x.length<7)continue;try{ReturnRecord r=new ReturnRecord(Integer.parseInt(x[0]),u(x[1]),u(x[2]));r.setStatus(ReturnStatus.valueOf(x[3]));if(!x[4].isBlank())r.setPickupDate(LocalDateTime.parse(x[4]));r.setInspectionNotes(u(x[5]));r.setRefundReference(u(x[6]));records.put(r.getOrderId(),r);}catch(Exception ignored){}}}catch(Exception e){System.out.println("Return history load failed: "+e.getMessage());}}
 private String b(String s){return Base64.getEncoder().encodeToString((s==null?"":s).getBytes(StandardCharsets.UTF_8));}private String u(String s){return s==null||s.isBlank()?"":new String(Base64.getDecoder().decode(s),StandardCharsets.UTF_8);}
}
